# Generated by Django 5.2.7 on 2025-10-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
