# Generated by Django 5.2.7 on 2025-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
